msm8994-common: releasetools: Make re.search work on python3
TypeError: cannot use a string pattern on a bytes-like object

Change-Id: I9e811f3d170402d23fd0448f1a21496a8c56bf88
(cherry picked from commit 39f0fcb484bf1b65a038e1571d4d2396da8e1915)